pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin_all_from "app/javascript/lib", under: "lib"
pin "highlight.js", to: "highlight/core.min.js"
pin "highlight.js/http", to: "highlight/http.min.js"
pin "highlight.js/bash", to: "highlight/bash.min.js"
pin "highlight.js/javascript", to: "highlight/javascript.min.js"
pin "highlight.js/xml", to: "highlight/xml.min.js"
pin "highlight.js/json", to: "highlight/json.min.js"
pin "highlight.js/css", to: "highlight/css.min.js"
pin "codemirror", to: "codemirror.min.js"
